export const dummyText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pulvinar rutrum auctor. Donec eu tincidunt ex. Vivamus gravida massa venenatis lobortis hendrerit. Nullam eget pulvinar lectus. Morbi est leo, suscipit nec iaculis non, finibus nec purus. Sed feugiat egestas ex, at iaculis magna blandit at. Proin quis lacinia ipsum, at imperdiet neque. Donec luctus vel neque eu gravida. Nulla sagittis magna eu sem convallis semper. Donec a diam arcu.

Vestibulum tempor lobortis purus at volutpat. Donec risus massa, accumsan vitae lectus nec, condimentum ultricies mi. Etiam rhoncus, sapien a luctus lacinia, dolor nisi pellentesque ligula, iaculis finibus risus sem dapibus tortor. Nam in mauris porttitor, luctus erat sed, fringilla sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis suscipit nec lacus ac tincidunt. Duis vel lectus at nulla fermentum convallis. Pellentesque vulputate ex eget est finibus posuere. Etiam odio dolor, dictum at purus et, porttitor tempus quam. Cras varius arcu vehicula tortor dignissim viverra. Mauris lobortis nisi ut libero blandit congue. Cras non euismod augue. Nam finibus ullamcorper suscipit.

Sed tortor velit, commodo sed est nec, aliquam mattis nunc. Mauris erat odio, varius a neque ac, hendrerit egestas tortor. Sed consectetur, augue sit amet suscipit semper, odio lacus tincidunt enim, in fringilla leo purus fermentum nulla. Nullam in nisl ut nisl convallis venenatis nec vitae enim. Curabitur maximus, magna a feugiat sagittis, sem mauris eleifend turpis, eu sagittis ex mi sit amet dolor. Praesent magna turpis, efficitur eu ex vitae, ullamcorper auctor neque. Sed sit amet magna ac arcu vehicula pulvinar in at ipsum. Cras tristique dui id erat tempus, eget pulvinar eros fringilla. Praesent commodo gravida venenatis. Vestibulum a massa augue. Aenean cursus, dui nec interdum sollicitudin, magna erat porttitor ex, suscipit tincidunt velit sapien non purus. Donec fringilla, nibh eget laoreet vehicula, libero sem vehicula ex, sed rutrum ligula lorem id felis. Vivamus augue risus, pellentesque aliquet eros commodo, egestas hendrerit eros. Duis placerat ligula quis bibendum finibus.

Etiam vel mi sit amet neque lobortis viverra aliquam eu enim. Vivamus luctus posuere diam et convallis. Pellentesque cursus turpis nec mi tempor, a pulvinar eros placerat. Vivamus elementum turpis mi, sit amet euismod enim venenatis eu. Aliquam tristique tristique elit. Vivamus sed nibh vel metus posuere blandit. Suspendisse potenti. Proin scelerisque nunc dui, a facilisis ligula aliquam non. Aliquam erat volutpat. Duis quis congue urna. Pellentesque magna felis, venenatis sed purus quis, feugiat imperdiet enim.

Etiam sed est nec massa ultrices luctus. In hac habitasse platea dictumst. Proin placerat condimentum pellentesque. Quisque scelerisque ante non mauris gravida, nec dapibus sapien lacinia. Aenean suscipit arcu ut dapibus tincidunt. Duis commodo ultrices enim in tincidunt. Proin lacinia magna quis nisl sagittis, id dictum nulla efficitur. Vestibulum tincidunt nisi tincidunt ipsum ornare pharetra. Phasellus posuere erat sed est pretium, non commodo elit ullamcorper. Integer ex erat, interdum eu elit nec, bibendum rhoncus ligula. Nam vestibulum sagittis ipsum eget varius. Nulla in luctus libero. Maecenas mollis risus tortor, et luctus mauris ullamcorper eu. In quis tristique metus. Suspendisse ut sodales arcu.`;
